site_name: Docs

# 0. Topic A isn't first in order. But it has all the desired sub-structure.
nav:
  - ...

# # 1. This method produces the unnecessary "topicA" folder:
# nav:
#   - TOPIC A: 
#     - ... | topicA/**
#   - ...

# # 2. This method flattens all sub-folders:
# nav:
#   - TOPIC A: 
#     - ... | flat | topicA/**
#   - ...


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search
  - awesome-pages

