site_name: Docs

# # 0. (the default) Topic A isn't first in order. But it has all the desired sub-structure.
# nav:
#   - ...

# # 1. This method produces the unnecessary "topicA" folder:
# nav:
#   - TOPIC A: 
#     - ... | topicA/**
#   - ...

# # 2. This method flattens all sub-folders:
# nav:
#   - TOPIC A: 
#     - ... | flat | topicA/**
#   - ...

# 3. Can set the order of topics like this!
nav:
  - my index: index.md
  - ... | topicA/**
  - ...
# BUT then: 
# - can't rename, e.g. to "TOPIC A"
# - can't include 'index.md' inside of topic A
#   (index.md must be in the top level: in docs/)


###############################################################################

# # Desired example:
# nav:
#   - TOPIC A: 
#     - my index: index.md
#     - ... | flat -1 | topicA/**
#   - ...


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search
  - awesome-pages
  