site_name: Docs

# # 0. (the default) Topic A isn't first in order. But it has all the desired sub-structure.
# nav:
#   - ...

# # 1. This method produces the unnecessary "topicA" folder:
# nav:
#   - TOPIC A: 
#     - ... | topicA/**
#   - ...

# # 2. This method flattens all sub-folders:
# nav:
#   - TOPIC A: 
#     - ... | flat | topicA/**
#   - ...


######################## other

# # Example with index.md (index.md be in the top level)
# nav:
#   - TOPIC A: 
#     - my index md: index.md
#     - ... | topicA/**  # here, I want the top folder to be removed with: flat -1
#   - ...

# 3. Can set the order of topics like this! 🎉
nav:
  - index.md
  - ... | topicA/**  # BUT: 1) can't rename to "TOPIC A", 2) can't include 'index.md' inside this topic
  - ...


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search
  - awesome-pages
  